### ISSUE TITLE
using --babel lint strange errors

### ISSUE THREAD

**Issue by deser** [STRML/JSXHint#59]
When i use --babel flag I get such errors:
1. "The body of a for in should be wrapped in an if statement to filter unwanted properties from the prototype."
2. The '__proto__' property is deprecated.

These errors fall in files that has react 13 classes.

**Comment by daumiller** [comment]
Also getting odd errors from generated code using `--babel`.
```
line 1, col 768, Read only.
line 1, col 957, 'parent' is already defined.
line 1, col 1915, The '__proto__' property is deprecated.
```

**Comment by STRML** [comment]
This is pretty common. Babel's more involved properties use some compact code that fails normal linting.

There's nothing to be done about it since JSXHint is really (transform -> lint) when it should be a smarter linter that understands JSX and ES6.

That smarter linter already exists: [ESLint](http://eslint.org/). JSXHint is no longer supported as ESLint does a far better job - and why have competing linter projects.
